# yaml-language-server: $schema=../schema.json
account:
  name: nifihub
  github_environment: prd

deployments:
- name: NIFIHUB_DEPLOYMENT
  deployment_type: SNOWFLAKE
  display_name: "NiFi Hub Deployment"
  comment: "NiFi Hub Deployment"
  runtimes:
    - name: NIFIHUB_RUNTIME_PRD
      database: OPENFLOW
      schema: OPENFLOW
      node_type: SMALL
      min_nodes: 1
      max_nodes: 1
      suspend: false
      execute_as_role: OPENFLOW_ADMIN
      display_name: "PRD Runtime"
      comment: "PRD Minimal runtime for hello-world flow"
      flow_registries:
        - name: nifihub
          type: org.apache.nifi.github.GitHubFlowRegistryClient
          properties:
            Repository Owner: sfc-gh-ohutuleac
            Repository Name: nifihub
            Authentication Type: PERSONAL_ACCESS_TOKEN
            Personal Access Token: ${{ secrets.NIFIHUB_REGISTRY_PAT }}
            Default Branch: prd
            Repository Path: flows
      flows:
      - name: "Example Flow to Snowflake"
        registry: nifihub
        bucket: examples
        flow: example-flow-to-snowflake
        version: latest
        start: true